name: _fam
channels:
- conda-forge
- nodefaults
dependencies:
- jupyterlab==2.1.5
- nodejs >= 12, <13
- python=3.7
- python-language-server
- pip
- pandas
- bqplot
- ipyvolume
- ipywebrtc
- hvplot
- datashader
- holoviews
- matplotlib-base
- altair
- jaeger
- importnb
- pip:
  - pidgy
  - poser
  - jupyter-starters==0.3.0a0 
  - jupyter-jaeger
  - jupyter-videochat ==0.1.1 
